repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: forbid-new-submodules

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: '2.1.6'
    hooks:
      - id: forbid-binary

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.2
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_docs
